export const SET_ACTIVATED_LIST_SUCCESS = 'SET_ACTIVATED_LIST_SUCCESS';
export const SET_BORROWING_LIST_SUCCESS = 'SET_BORROWING_LIST_SUCCESS';
export const SET_ADDRESS_SUCCESS = 'SET_ADDRESS_SUCCESS';
export const SET_ADDRESS_FAILURE = 'SET_ADDRESS_FAILURE';
export const SET_CURRENCY_SUCCESS = 'SET_CURRENCY_SUCCESS';
export const SET_LENDING_LIST_SUCCESS = 'SET_LENDING_LIST_SUCCESS';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_UNUSED_LIST_SUCCESS = 'SET_UNUSED_LIST_SUCCESS';
