export const SET_NETWORK_SUCCESS = 'SET_NETWORK_SUCCESS';
export const SET_NETWORK_FAILURE = 'SET_NETWORK_FAILURE';
export const UPDATE_ENABLED_STATUS = 'UPDATE_ENABLED_STATUS';
export const UPDATE_NAMESPACE_STATUS = 'UPDATE_NAMESPACE_STATUS';
